### ISSUE TITLE
Error while performing MetaCHIP PG step

### ISSUE THREAD

**Issue by chenziwu5** [songweizhi/MetaCHIP#1]
Hi,
Thank you for developing a great tools！
when I run this command: MetaCHIP PG -p S1_Spr -r o -t 18, something went wrong but I get no idea that how to debug this.
Here is my error report, waitting on the line:). thank you!

Traceback (most recent call last):
  File "/home/chenziwu/anaconda3/envs/metachip_py27/bin/MetaCHIP", line 177, in <module>
    PG(args, config_dict)
  File "/home/chenziwu/anaconda3/envs/metachip_py27/lib/python2.7/site-packages/MetaCHIP/PG.py", line 825, in PG
    pwd_AggregateRanger_exe = config_dict['AggregateRanger_linux']
KeyError: 'AggregateRanger_linux'

I have successfully completed the first two steps：MetaCHIP PI  and MetaCHIP BM.
Here is the report of the first two steps:
MetaCHIP PI -i /home/chenziwu/data/metachip_test/metawrap_bins -x fa -taxon s1_spr_total.txt -r o -p S1_Spr -t 18
[2019-04-16 16:38:05] Input genomes clustered into 20 groups
[2019-04-16 16:38:05] Ignored 3 genome(s) with unknown classification at specified level
[2019-04-16 16:38:06] Grouping file exported to: S1_Spr_o20_grouping.txt
[2019-04-16 16:38:07] Grouping stats exported to: S1_Spr_o20_grouping.png
[2019-04-16 16:38:07] Calculating the size of input genomes
[2019-04-16 16:38:09] The size of input genomes exported to: S1_Spr_all_genome_size.txt
[2019-04-16 16:38:09] Running Prodigal with 18 cores for all input genomes
[2019-04-16 16:40:53] Copying annotation files of qualified genomes to corresponding folders
[2019-04-16 16:40:53] Running Hmmsearch with 18 cores
[2019-04-16 16:40:59] Running Hmmalign with 18 cores
[2019-04-16 16:41:05] Concatenating alignments
[2019-04-16 16:41:05] Removing columns from concatenated alignment represented by <50% of genomes and with an amino acid consensus <25%
[2019-04-16 16:41:10] Running FastTree
[2019-04-16 16:41:43] Species tree exported to: S1_Spr_o20_species_tree.newick
[2019-04-16 16:41:53] Commands for running blastn exported to: S1_Spr_all_blastn_commands.txt
[2019-04-16 16:41:53] Running blastn for all input genomes with 18 cores, blast results exported to: S1_Spr_MetaCHIP_wd/S1_Spr_all_blastn_results
[2019-04-16 17:36:40] PrepIn done!
MetaCHIP BM -p S1_Spr -r o -t 18
[2019-04-16 18:47:35] Found grouping file S1_Spr_o20_grouping.txt, input genomes were clustered into 20 groups
[2019-04-16 18:47:35] Filtering blast matches with the following criteria: Query genome != Subject genome, Alignment length >= 200bp and coverage >= 75%
[2019-04-16 18:47:36] Combining filtered blastn results
[2019-04-16 18:47:36] Get group-to-group identities with 18 cores
[2019-04-16 18:47:38] Plotting identity distribution between each pair of groups
[2019-04-16 18:47:39] Analyzing Blast hits to get HGT candidates with 18 cores
[2019-04-16 18:47:39] Plotting flanking regions with 18 cores
[2019-04-16 18:49:38] Extracting nc sequences for BM predicted HGTs
[2019-04-16 18:49:42] Deleting temporary files
[2019-04-16 18:49:42] Done for Best-match approach!

**Comment by songweizhi** [comment]
the BM and PG modules have now been integrated as BP module.
