### ISSUE TITLE
Error running Ranger-DTL2 in BP module

### ISSUE THREAD

**Issue by Cables4lyfe** [songweizhi/MetaCHIP#10]
Hello
When I try to test run a fresh installion of MetaCHIP I get the following error:

$ MetaCHIP BP -p Test -r c -t 20
[2020-10-19 13:21:39] Filtering blastn results with the following criteria: Query genome != Subject genome, Alignment length >= 200bp and coverage >= 75%.
[2020-10-19 13:21:39] HGT Detection among classes: input genomes were clustered into 5 classes.
[2020-10-19 13:21:39] HGT Detection among classes: Best-match approach.
[2020-10-19 13:21:39] HGT Detection among classes: get group-to-group identities with 20 cores.
[2020-10-19 13:21:39] HGT Detection among classes: analyzing Blast hits with 20 cores.
[2020-10-19 13:21:39] HGT Detection among classes: plotting flanking regions with 20 cores.
[2020-10-19 13:21:40] HGT Detection among classes: get sequences of BM predicted HGT candidates.
[2020-10-19 13:21:40] HGT Detection among classes: done for BM approach!
[2020-10-19 13:21:40] HGT Detection among classes: get gene/genome members in gene/species tree for BM predicted HGT candidates.
[2020-10-19 13:21:40] HGT Detection among classes: prepare Test_c_combined_faa.fasta subset.
[2020-10-19 13:21:40] HGT Detection among classes: get species and gene tree for 2 BM approach identified HGTs.
[2020-10-19 13:21:41] HGT Detection among classes: running Ranger-DTL2.
multiprocessing.pool.RemoteTraceback:
"""
Traceback (most recent call last):
  File "/home/casper/.conda/envs/py36/lib/python3.6/multiprocessing/pool.py", line 119, in worker
    result = (True, func(*args, **kwds))
  File "/home/casper/.conda/envs/py36/lib/python3.6/multiprocessing/pool.py", line 44, in mapstar
    return list(map(*args))
  File "/home/casper/.conda/envs/py36/lib/python3.6/site-packages/MetaCHIP/BP.py", line 1232, in Ranger_worker
    species_tree = Tree(pwd_species_tree_newick_no_hyphen_in_branch_length, format=0)
  File "/home/casper/.local/lib/python3.6/site-packages/ete3/coretype/tree.py", line 213, in __init__
    quoted_names=quoted_node_names)
  File "/home/casper/.local/lib/python3.6/site-packages/ete3/parser/newick.py", line 266, in read_newick
    return _read_newick_from_string(nw, root_node, matcher, format, quoted_names)
  File "/home/casper/.local/lib/python3.6/site-packages/ete3/parser/newick.py", line 341, in _read_newick_from_string
    _read_node_data(closing_internal, current_parent, "internal", matcher, formatcode)
  File "/home/casper/.local/lib/python3.6/site-packages/ete3/parser/newick.py", line 445, in _read_node_data
    raise NewickError("Unexpected newick format '%s' " %subnw[0:50])
ete3.parser.newick.NewickError: Unexpected newick format ':1.00:0.14535'
You may want to check other newick loading flags like 'format' or 'quoted_node_names'.
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/casper/.conda/envs/py36/bin/MetaCHIP", line 168, in <module>
    BP(args, config_dict)
  File "/home/casper/.conda/envs/py36/lib/python3.6/site-packages/MetaCHIP/BP.py", line 2370, in BP
    pool.map(Ranger_worker, list_for_multiple_arguments_Ranger)
  File "/home/casper/.conda/envs/py36/lib/python3.6/multiprocessing/pool.py", line 266, in map
    return self._map_async(func, iterable, mapstar, chunksize).get()
  File "/home/casper/.conda/envs/py36/lib/python3.6/multiprocessing/pool.py", line 644, in get
    raise self._value
ete3.parser.newick.NewickError: Unexpected newick format ':1.00:0.14535'
You may want to check other newick loading flags like 'format' or 'quoted_node_names'.

From my understanding, it seems the newick file produced in one step is in format 5 and the next step wants it to be in format 0.

Any help would be highly appreciated!

**Comment by songweizhi** [comment]
Hi,

Thanks for using MetaCHIP.
I’d like to know is it possible to share with me your MAGs and their taxonomic classifications?
Your files will only be used for debugging.

Cheers,
Weizhi

**Comment by Cables4lyfe** [comment]
Hello

This was a test run to see if the program worked. The files are the example files you provided:

[Example.zip](https://github.com/songweizhi/MetaCHIP/files/5401587/Example.zip)

**Comment by songweizhi** [comment]
It works all good on my side with the example dataset, can you please let me know the version of your ETE3 package? I am using 3.1.1.

**Comment by Cables4lyfe** [comment]
I am using ETE3 v. 3.1.2.

**Comment by Cables4lyfe** [comment]
I did a fresh install on another server which seemed to solve the issue
