### ISSUE TITLE
Error: BP step, file not found

### ISSUE THREAD

**Issue by mmpust** [songweizhi/MetaCHIP#13]
Hey,
thanks for developing and maintaining metaCHIP. It seems to be of high significance and I really would like to use it to look into my metagenomics data. However, I get an error message when executing the MetaCHIP BP command. I know the question has been asked before but there is no final answer yet. The PI step works fine with the following output:
```
[2021-01-01 00:44:06] Input genomes grouped into 3 phyla.
[2021-01-01 00:44:06] Input genomes grouped into 3 classes.
[2021-01-01 00:44:07] Input genomes grouped into 5 orders.
[2021-01-01 00:44:07] Input genomes grouped into 5 families.
[2021-01-01 00:44:08] Input genomes grouped into 6 genera.
[2021-01-01 00:44:08] Total number of qualified genomes for HGT detection: 33.
[2021-01-01 00:44:09] Grouping file exported to: 0_core_grouping_p3.txt.
[2021-01-01 00:44:09] Grouping file exported to: 0_core_grouping_c3.txt.
[2021-01-01 00:44:10] Grouping file exported to: 0_core_grouping_o5.txt.
[2021-01-01 00:44:10] Grouping file exported to: 0_core_grouping_f5.txt.
[2021-01-01 00:44:11] Grouping file exported to: 0_core_grouping_g6.txt.
[2021-01-01 00:44:11] Running Prodigal for 33 qualified genomes with 1 cores (1-3 minutes pre genome per core).
[2021-01-01 00:53:44] Get SCG tree: running hmmsearch with 1 cores.
[2021-01-01 00:54:25] Get SCG tree: running hmmalign with 1 cores.
[2021-01-01 00:54:32] Get SCG tree: concatenating alignments.
[2021-01-01 00:54:32] Get SCG tree: removing columns from concatenated alignment represented by <50% of genomes and with amino acid consensus <25%.
[2021-01-01 00:54:32] Get SCG tree: running FastTree.
[2021-01-01 00:54:54] SCG tree exported to: 0_core_pcofg_SCG_tree.newick.
[2021-01-01 00:54:55] Making blast database.
[2021-01-01 00:54:57] Blastn commands exported to: 0_core_pcofg_blastn_commands.txt.
[2021-01-01 00:54:57] Running blastn for 33 qualified genomes with 1 cores.
[2021-01-01 01:22:50] Blast results exported to: 0_core_MetaCHIP_wd/0_core_pcofg_blastn_results.
[2021-01-01 01:22:50] PI step done!
```
However, when running the BS step, I get the following error message.
```
[2021-01-01 13:33:50] Filtering blastn results with the following criteria: Query genome != Subject genome, Alignment length >= 200bp and coverage >= 75%.
[2021-01-01 13:33:53] HGT Detection among phyla: input genomes were clustered into 3 phyla.
[2021-01-01 13:33:53] HGT Detection among phyla: Best-match approach.
[2021-01-01 13:33:53] HGT Detection among phyla: get group-to-group identities with 1 cores.
[2021-01-01 13:33:56] HGT Detection among phyla: analyzing Blast hits with 1 cores.
[2021-01-01 13:34:02] HGT Detection among phyla: plotting flanking regions with 1 cores.
Command line argument error: Argument "subject". File is not accessible:  `0_core_MetaCHIP_wd/0_core_HGT_ip90_al200bp_c75_ei80_f10kbp_p3/0_core_p3_Flanking_region_plots/Neis>
Command line argument error: Argument "subject". File is not accessible:  `0_core_MetaCHIP_wd/0_core_HGT_ip90_al200bp_c75_ei80_f10kbp_p3/0_core_p3_Flanking_region_plots/Neis>
multiprocessing.pool.RemoteTraceback:
"""
Traceback (most recent call last):
  File "/miniconda3/lib/python3.7/multiprocessing/pool.py", line 121, in worker
    result = (True, func(*args, **kwds))
  File "/miniconda3/lib/python3.7/multiprocessing/pool.py", line 44, in mapstar
    return list(map(*args))
  File "/miniconda3/lib/python3.7/site-packages/MetaCHIP/BP.py", line 861, in get_gbk_blast_act2
    for blast_hit in open(output_c_full_len):
FileNotFoundError: [Errno 2] No such file or directory: '0_core_MetaCHIP_wd/0_core_HGT_ip90_al200bp_c75_ei80_f10kbp_p3/0_core_p3_Flanking_region_plots/Neis>
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/miniconda3/bin/MetaCHIP", line 168, in <module>
    BP(args, config_dict)
  File "/miniconda3/lib/python3.7/site-packages/MetaCHIP/BP.py", line 2164, in BP
    pool_flanking_regions.map(get_gbk_blast_act2, list_for_multiple_arguments_flanking_regions)
  File "/miniconda3/lib/python3.7/multiprocessing/pool.py", line 268, in map
    return self._map_async(func, iterable, mapstar, chunksize).get()
  File "/miniconda3/lib/python3.7/multiprocessing/pool.py", line 657, in get
    raise self._value
FileNotFoundError: [Errno 2] No such file or directory: '0_core_MetaCHIP_wd/0_core_HGT_ip90_al200bp_c75_ei80_f10kbp_p3/0_core_p3_Flanking_region_plots/Neis>
```

The commands I use are:

```
MetaCHIP PI  \
-p 0_core \
-r pcofg \
-i hgt-metachip/prep_gtdbtk/0_core_renamed \
-x fa \
-taxon hgt-metachip/prep_gtdbtk/0_core_renamed/classifying_genomes/gtdbtk.bac120.summary.tsv
```

```
MetaCHIP BP  \
-p 0_core \
-r pcofg
```

Can you give me any advice on what to do now?
Cheers,
Marie

**Comment by songweizhi** [comment]
Hi Marie,

Thanks for using MetaCHIP, please refers to issue #12 for a possible solution.
if the problem still exist, could you please share with me some of yout input files for debugging?
 
Cheers,
Weizhi

**Comment by mmpust** [comment]
Hey Weizhi,
thanks for your reply! I abbreviated file names and .FASTA headers, now it is running.
Cheers,
Marie
