### ISSUE TITLE
Bio.Alphabet has been removed from Biopython

### ISSUE THREAD

**Issue by SophieS9** [songweizhi/MetaCHIP#14]
Dear MetaCHIP team,

I've just installed MetaCHIP via pip3 install, however it is not functioning. I'm seeing an error associated with the Bio.Alphabet module from Biopython as follows:

```
$ MetaCHIP
Traceback (most recent call last):
  File "/opt/software/uoa/2020/apps/python/pypi/3.7/bin/MetaCHIP", line 24, in <module>
    from MetaCHIP.PI import PI
  File "/opt/software/uoa/2020/apps/python/pypi/3.7/lib/python3.7/site-packages/MetaCHIP/PI.py", line 31, in <module>
    from Bio.Alphabet import IUPAC, generic_dna
  File "/opt/software/uoa/2020/apps/python/pypi/3.7/lib/python3.7/site-packages/Bio/Alphabet/__init__.py", line 21, in <module>
    "Bio.Alphabet has been removed from Biopython. In many cases, the alphabet can simply be ignored and removed from scripts. In a few cases, you may need to specify the ``molecule_type`` as an annotation on a SeqRecord for your script to work correctly. Please see https://biopython.org/wiki/Alphabet for more information."
ImportError: Bio.Alphabet has been removed from Biopython. In many cases, the alphabet can simply be ignored and removed from scripts. In a few cases, you may need to specify the ``molecule_type`` as an annotation on a SeqRecord for your script to work correctly. Please see https://biopython.org/wiki/Alphabet for more information.
```

Any suggestions on how to fix this? We have the most recent version of biopython installed. 

Thanks,

Sophie

**Comment by SophieS9** [comment]
As a note, I tried running with an older version of BioPython (1.7) but this threw a different error:

```
MetaCHIP PI -p Test -r s -i Genomes/ -x fasta -taxon taxa.txt 
Traceback (most recent call last):
  File "/opt/software/uoa/2020/apps/python/pypi/3.7/bin/MetaCHIP", line 24, in <module>
    from MetaCHIP.PI import PI
  File "/opt/software/uoa/2020/apps/python/pypi/3.7/lib/python3.7/site-packages/MetaCHIP/PI.py", line 29, in <module>
    from Bio import SeqIO, AlignIO, Align
  File "/opt/software/uoa/2020/apps/python/pypi/3.7/lib/python3.7/site-packages/Bio/SeqIO/__init__.py", line 658
    raise ValueError("No records found in handle") from None
                                                      ^
SyntaxError: invalid syntax
```

**Comment by songweizhi** [comment]
Hi，

I have updated MetaCHIP to make it compatible with the latest version of Biopython. Please update both MetaCHIP (1.10.3) and Biopython (1.78) and see if the error still exist.

Cheers,
Weizhi

**Comment by SophieS9** [comment]
Thanks Weizhi, this is working now!

**Comment by nick-youngblut** [comment]
>Please update both MetaCHIP (1.10.3) and Biopython (1.78) and see if the error still exist.

The bioconda recipe for MetaCHIP still requires `biopython <=1.77`:  https://github.com/bioconda/bioconda-recipes/blob/master/recipes/metachip/meta.yaml
