### ISSUE TITLE
Find HGT between genes of different genomes

### ISSUE THREAD

**Issue by ga23981** [songweizhi/MetaCHIP#17]
I made multifasta files of genes of interest of several genomes and used them as input files in a directory called genomes as following
singularity exec /apps/singularity-images/metachip_1.10.2.sif MetaCHIP PI -p pantoea -g customised_grouping.txt -t 30 -i genomes -x fasta

customised_grouping.txt file looks as following:
A,PNA_99_2
A,PNA_99_3
A,PNA_99_6
A,PNA_99_7
A,PNA_99_8
A,PNA_99_9
B,PANS_2_1
B,PANS_4_2
B,PANS_99_32
B,PNA_07_13
B,PNA_07_14
B,PNA_98_11
B,PNA_98_3
B,PNA_98_7

Getting an error:

WARNING: Skipping mount /var/singularity/mnt/session/etc/resolv.conf [files]: /etc/resolv.conf doesn't exist in container

Error: File existence/permissions problem in trying to open HMM file pantoea_MetaCHIP_wd/pantoea_x_get_SCG_tree_wd/pantoea_x_hmm_profile_fetched/.hmm.
HMM file pantoea_MetaCHIP_wd/pantoea_x_get_SCG_tree_wd/pantoea_x_hmm_profile_fetched/.hmm not found (nor an .h3m binary of it)
Traceback (most recent call last):
  File "/usr/local/bin/MetaCHIP", line 165, in <module>
    PI(args, MetaCHIP_config.config_dict)
  File "/usr/local/lib/python3.8/site-packages/MetaCHIP/PI.py", line 974, in PI
    remove_low_cov_and_consensus_columns(pwd_combined_alignment_file_tmp, minimal_cov_in_msa, min_consensus_in_msa, pwd_combined_alignment_file)
  File "/usr/local/lib/python3.8/site-packages/MetaCHIP/PI.py", line 537, in remove_low_cov_and_consensus_columns
    alignment_cov = remove_low_cov_columns(alignment, minimal_cov)
  File "/usr/local/lib/python3.8/site-packages/MetaCHIP/PI.py", line 496, in remove_low_cov_columns
    alignment_new = remove_columns_from_msa(alignment_in, low_cov_columns)
  File "/usr/local/lib/python3.8/site-packages/MetaCHIP/PI.py", line 464, in remove_columns_from_msa
    segment_value = alignment_in[:, segment[0]]
  File "/usr/local/lib/python3.8/site-packages/Bio/Align/__init__.py", line 848, in __getitem__
    new = MultipleSeqAlignment(
  File "/usr/local/lib/python3.8/site-packages/Bio/Align/__init__.py", line 170, in __init__
    self.extend(records)
  File "/usr/local/lib/python3.8/site-packages/Bio/Align/__init__.py", line 533, in extend
    rec = next(records)
  File "/usr/local/lib/python3.8/site-packages/Bio/Align/__init__.py", line 849, in <genexpr>
    (rec[col_index] for rec in self._records[row_index]), self._alphabet
  File "/usr/local/lib/python3.8/site-packages/Bio/SeqRecord.py", line 524, in __getitem__
    raise ValueError("Invalid index")
ValueError: Invalid index

I can also share my input genome files if needed.

**Comment by songweizhi** [comment]
Can you please update MetaCHIP to version 1.10.3 and try again?

**Comment by ga23981** [comment]
I tried with new version of MetaCHIP

MetaCHIP PI -p pantoea -g customised_grouping.txt -t 30 -i genomes -x fasta
MetaCHIP BP -p pantoea -g customised_grouping.txt -t 30

Got the following error:

multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/apps/eb/Python/3.7.4-GCCcore-8.3.0/lib/python3.7/multiprocessing/pool.py", line 121, in worker
    result = (True, func(*args, **kwds))
  File "/apps/eb/Python/3.7.4-GCCcore-8.3.0/lib/python3.7/multiprocessing/pool.py", line 44, in mapstar
    return list(map(*args))
  File "/apps/eb/MetaCHIP/1.10.3-foss-2019b-Python-3.7.4/lib/python3.7/site-packages/MetaCHIP/PI.py", line 233, in prodigal_worker
    prodigal_parser(pwd_input_genome, pwd_output_sco, input_genome_basename, pwd_prodigal_output_folder)
  File "/apps/eb/MetaCHIP/1.10.3-foss-2019b-Python-3.7.4/lib/python3.7/site-packages/MetaCHIP/PI.py", line 202, in prodigal_parser
    SeqIO.write(current_SeqRecord, bin_gbk_file_handle, 'genbank')
  File "/apps/eb/Biopython/1.75-foss-2019b-Python-3.7.4/lib/python3.7/site-packages/Bio/SeqIO/__init__.py", line 561, in write
    count = writer_class(fp).write_file(sequences)
  File "/apps/eb/Biopython/1.75-foss-2019b-Python-3.7.4/lib/python3.7/site-packages/Bio/SeqIO/Interfaces.py", line 254, in write_file
    count = self.write_records(records)
  File "/apps/eb/Biopython/1.75-foss-2019b-Python-3.7.4/lib/python3.7/site-packages/Bio/SeqIO/Interfaces.py", line 239, in write_records
    self.write_record(record)
  File "/apps/eb/Biopython/1.75-foss-2019b-Python-3.7.4/lib/python3.7/site-packages/Bio/SeqIO/InsdcIO.py", line 969, in write_record
    self._write_the_first_line(record)
  File "/apps/eb/Biopython/1.75-foss-2019b-Python-3.7.4/lib/python3.7/site-packages/Bio/SeqIO/InsdcIO.py", line 719, in _write_the_first_line
    raise ValueError("Need a Nucleotide or Protein alphabet")
ValueError: Need a Nucleotide or Protein alphabet
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/apps/eb/MetaCHIP/1.10.3-foss-2019b-Python-3.7.4/bin/MetaCHIP", line 165, in <module>
    PI(args, MetaCHIP_config.config_dict)
  File "/apps/eb/MetaCHIP/1.10.3-foss-2019b-Python-3.7.4/lib/python3.7/site-packages/MetaCHIP/PI.py", line 870, in PI
    pool.map(prodigal_worker, list_for_multiple_arguments_Prodigal)
  File "/apps/eb/Python/3.7.4-GCCcore-8.3.0/lib/python3.7/multiprocessing/pool.py", line 268, in map
    return self._map_async(func, iterable, mapstar, chunksize).get()
  File "/apps/eb/Python/3.7.4-GCCcore-8.3.0/lib/python3.7/multiprocessing/pool.py", line 657, in get
    raise self._value
ValueError: Need a Nucleotide or Protein alphabet

**Comment by ga23981** [comment]
Getting the following error:
[2021-03-04 10:52:21] No blastn reaults found in pantoea_x_blastn_results, please run all-vs-all blastn before the BP step!
Do I have to run all vs all blast separately. Is there a script in metaCHIP that can do it?

**Comment by ga23981** [comment]
The PI command generated empty .faa, .ffn, .gbk and .sco files. What could be the possible reason for this? If needed I can share one or all of my input fasta files. Just to reiterate all the fasta files contain only 12-15 genes that I want to analyze for HGT.

**Comment by songweizhi** [comment]
please share with me some of your input files so I can look into it, thanks,
Weizhi

**Comment by ga23981** [comment]
Hello Weizhi,
Please see attached some of the fasta files.

Let me know if you need any more details.

Thank you,
Gaurav

**Comment by ga23981** [comment]
After I updated the biopython version, I am getting the following error
using the files I shared with you. If needed I can share all the files with
you.

Error: File existence/permissions problem in trying to open HMM file
pantoea_MetaCHIP_wd/pantoea_x_get_SCG_tree_wd/pantoea_x_hmm_profile_fetched/.hmm.

HMM file
pantoea_MetaCHIP_wd/pantoea_x_get_SCG_tree_wd/pantoea_x_hmm_profile_fetched/.hmm
not found (nor an .h3m binary of it)


Traceback (most recent call last):

  File "/apps/eb/MetaCHIP/1.10.3-foss-2019b-Python-3.8.2/bin/MetaCHIP",
line 165, in <module>

    PI(args, MetaCHIP_config.config_dict)

  File
"/apps/eb/MetaCHIP/1.10.3-foss-2019b-Python-3.8.2/lib/python3.8/site-packages/MetaCHIP/PI.py",
line 958, in PI

    remove_low_cov_and_consensus_columns(pwd_combined_alignment_file_tmp,
minimal_cov_in_msa, min_consensus_in_msa, pwd_combined_alignment_file)

  File
"/apps/eb/MetaCHIP/1.10.3-foss-2019b-Python-3.8.2/lib/python3.8/site-packages/MetaCHIP/PI.py",
line 521, in remove_low_cov_and_consensus_columns

    alignment_cov = remove_low_cov_columns(alignment, minimal_cov)

  File
"/apps/eb/MetaCHIP/1.10.3-foss-2019b-Python-3.8.2/lib/python3.8/site-packages/MetaCHIP/PI.py",
line 480, in remove_low_cov_columns

    alignment_new = remove_columns_from_msa(alignment_in, low_cov_columns)

  File
"/apps/eb/MetaCHIP/1.10.3-foss-2019b-Python-3.8.2/lib/python3.8/site-packages/MetaCHIP/PI.py",
line 448, in remove_columns_from_msa

    segment_value = alignment_in[:, segment[0]]

  File
"/apps/eb/Biopython/1.78-foss-2019b-Python-3.8.2/lib/python3.8/site-packages/Bio/Align/__init__.py",
line 823, in __getitem__

    new = MultipleSeqAlignment(

  File
"/apps/eb/Biopython/1.78-foss-2019b-Python-3.8.2/lib/python3.8/site-packages/Bio/Align/__init__.py",
line 162, in __init__

    self.extend(records)

  File
"/apps/eb/Biopython/1.78-foss-2019b-Python-3.8.2/lib/python3.8/site-packages/Bio/Align/__init__.py",
line 514, in extend

    rec = next(records)

  File
"/apps/eb/Biopython/1.78-foss-2019b-Python-3.8.2/lib/python3.8/site-packages/Bio/Align/__init__.py",
line 824, in <genexpr>

    (rec[col_index] for rec in self._records[row_index])

  File
"/apps/eb/Biopython/1.78-foss-2019b-Python-3.8.2/lib/python3.8/site-packages/Bio/SeqRecord.py",
line 520, in __getitem__

    raise ValueError("Invalid index")

ValueError: Invalid index

Thank you,
Gaurav

**Comment by bahiyahazli** [comment]
Hello, I am getting the same error for my data. Do you perhaps successfully resolve this issue?

Thank you
