### ISSUE TITLE
FileNotFoundError

### ISSUE THREAD

**Issue by nick-youngblut** [songweizhi/MetaCHIP#23]
Command:

```
MetaCHIP PI -r g -t 8   -x fna -p tmp/metachip     -i genomes  -taxon gtdbtk_summary.tsv
```

Error:

```
Traceback (most recent call last):
  File "/ebio/abt3_projects/software/dev/ll_pipelines/llg/.snakemake/conda/393a800324f63ba3ae6b73503f7745cc/bin/MetaCHIP", line 165, in <module>
    PI(args, MetaCHIP_config.config_dict)
  File "/ebio/abt3_projects/software/dev/ll_pipelines/llg/.snakemake/conda/393a800324f63ba3ae6b73503f7745cc/lib/python3.8/site-packages/MetaCHIP/PI.py", line 651, in PI
    force_create_folder(pwd_log_folder)
  File "/ebio/abt3_projects/software/dev/ll_pipelines/llg/.snakemake/conda/393a800324f63ba3ae6b73503f7745cc/lib/python3.8/site-packages/MetaCHIP/PI.py", line 59, in force_create_folder
    os.mkdir(folder_to_create)
FileNotFoundError: [Errno 2] No such file or directory: 'tmp/metachip_MetaCHIP_wd/tmp/metachip_g_log_files'
```

[Conda env](https://anaconda.org/bioconda/metachip):

```
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                 conda_forge    conda-forge
_openmp_mutex             4.5                       1_gnu    conda-forge
_r-mutex                  1.0.1               anacondar_1    conda-forge
alsa-lib                  1.2.3                h516909a_0    conda-forge
binutils_impl_linux-64    2.36.1               h193b22a_2    conda-forge
binutils_linux-64         2.36                 hf3e587d_1    conda-forge
biopython                 1.77             py38h1e0a361_1    conda-forge
blast                     2.12.0          pl5262h3289130_0    bioconda
bwidget                   1.9.14                        0    conda-forge
bzip2                     1.0.8                h7f98852_4    conda-forge
c-ares                    1.17.2               h7f98852_0    conda-forge
ca-certificates           2021.7.5             h06a4308_1
cairo                     1.16.0            h6cf1ce9_1008    conda-forge
certifi                   2021.5.30        py38h578d9bd_0    conda-forge
curl                      7.79.0               hea6ffbf_0    conda-forge
cycler                    0.10.0                     py_2    conda-forge
dbus                      1.13.18              hb2f20db_0
entrez-direct             15.6                 he881be0_0    bioconda
ete3                      3.1.2              pyh9f0ad1d_0    conda-forge
expat                     2.4.1                h9c3ff4c_0    conda-forge
fasttree                  2.1.10               h779adbc_5    bioconda
font-ttf-dejavu-sans-mono 2.37                 hab24e00_0    conda-forge
font-ttf-inconsolata      3.000                h77eed37_0    conda-forge
font-ttf-source-code-pro  2.038                h77eed37_0    conda-forge
font-ttf-ubuntu           0.83                 hab24e00_0    conda-forge
fontconfig                2.13.1            hba837de_1005    conda-forge
fonts-conda-ecosystem     1                             0    conda-forge
fonts-conda-forge         1                             0    conda-forge
freetype                  2.10.4               h0708190_1    conda-forge
fribidi                   1.0.10               h516909a_0    conda-forge
gcc_impl_linux-64         9.4.0                h03d3576_8    conda-forge
gcc_linux-64              9.4.0                h391b98a_1    conda-forge
gettext                   0.21.0               hf68c758_0
gfortran_impl_linux-64    9.4.0                h0003116_8    conda-forge
gfortran_linux-64         9.4.0                hf0ab688_1    conda-forge
glib                      2.68.4               h9c3ff4c_1    conda-forge
glib-tools                2.68.4               h9c3ff4c_1    conda-forge
graphite2                 1.3.14               h23475e2_0
gsl                       2.7                  he838d99_0    conda-forge
gst-plugins-base          1.18.5               hf529b03_0    conda-forge
gstreamer                 1.18.5               h76c114f_0    conda-forge
gxx_impl_linux-64         9.4.0                h03d3576_8    conda-forge
gxx_linux-64              9.4.0                h0316aca_1    conda-forge
harfbuzz                  2.9.1                h83ec7ef_0    conda-forge
hmmer                     3.3.2                h1b792b2_1    bioconda
icu                       68.1                 h58526e2_0    conda-forge
jbig                      2.1               h7f98852_2003    conda-forge
jpeg                      9d                   h516909a_0    conda-forge
kernel-headers_linux-64   2.6.32              he073ed8_14    conda-forge
kiwisolver                1.3.2            py38h1fd1430_0    conda-forge
krb5                      1.19.2               hcc1bbae_0    conda-forge
lcms2                     2.12                 hddcbb42_0    conda-forge
ld_impl_linux-64          2.36.1               hea4e1c9_2    conda-forge
lerc                      2.2.1                h9c3ff4c_0    conda-forge
libblas                   3.9.0           11_linux64_openblas    conda-forge
libcblas                  3.9.0           11_linux64_openblas    conda-forge
libclang                  11.1.0          default_ha53f305_1    conda-forge
libcurl                   7.79.0               h2574ce0_0    conda-forge
libdeflate                1.7                  h7f98852_5    conda-forge
libedit                   3.1.20210714         h7f8727e_0
libev                     4.33                 h516909a_1    conda-forge
libevent                  2.1.10               hcdb4288_3    conda-forge
libffi                    3.4.2                h9c3ff4c_1    conda-forge
libgcc-devel_linux-64     9.4.0                hd854feb_8    conda-forge
libgcc-ng                 11.2.0               h1d223b6_8    conda-forge
libgfortran-ng            11.2.0               h69a702a_8    conda-forge
libgfortran5              11.2.0               h5c6108e_8    conda-forge
libglib                   2.68.4               h174f98d_1    conda-forge
libgomp                   11.2.0               h1d223b6_8    conda-forge
libiconv                  1.16                 h516909a_0    conda-forge
liblapack                 3.9.0           11_linux64_openblas    conda-forge
libllvm11                 11.1.0               hf817b99_2    conda-forge
libnghttp2                1.43.0               h812cca2_0    conda-forge
libogg                    1.3.5                h27cfd23_1
libopenblas               0.3.17          pthreads_h8fe5266_1    conda-forge
libopus                   1.3.1                h7f98852_1    conda-forge
libpng                    1.6.37               hed695b0_2    conda-forge
libpq                     13.3                 hd57d9b9_0    conda-forge
libsanitizer              9.4.0                h79bfe98_8    conda-forge
libssh2                   1.10.0               ha56f1ee_0    conda-forge
libstdcxx-devel_linux-64  9.4.0                hd854feb_8    conda-forge
libstdcxx-ng              11.2.0               he4da1e4_8    conda-forge
libtiff                   4.3.0                hf544144_1    conda-forge
libuuid                   2.32.1            h14c3975_1000    conda-forge
libvorbis                 1.3.7                he1b5a44_0    conda-forge
libwebp-base              1.2.1                h7f98852_0    conda-forge
libxcb                    1.14                 h7b6447c_0
libxkbcommon              1.0.3                he3ba5ed_0    conda-forge
libxml2                   2.9.12               h72842e0_0    conda-forge
libxslt                   1.1.33               h15afd5d_2    conda-forge
lxml                      4.6.3            py38hf1fe3a4_0    conda-forge
lz4-c                     1.9.3                h9c3ff4c_1    conda-forge
mafft                     7.487                h779adbc_0    bioconda
make                      4.3                  hd18ef5c_1    conda-forge
matplotlib-base           3.4.3            py38hf4fb855_0    conda-forge
metachip                  1.10.5             pyh5e36f6f_0    bioconda
mysql-common              8.0.25               ha770c72_2    conda-forge
mysql-libs                8.0.25               hfa10184_2    conda-forge
ncurses                   6.2                  h58526e2_4    conda-forge
nspr                      4.30                 h9c3ff4c_0    conda-forge
nss                       3.69                 hb5efdd6_0    conda-forge
numpy                     1.21.2           py38he2449b9_0    conda-forge
olefile                   0.46               pyh9f0ad1d_1    conda-forge
openjpeg                  2.4.0                hb52868f_1    conda-forge
openssl                   1.1.1l               h7f98852_0    conda-forge
pango                     1.48.10              hb8ff022_0    conda-forge
pcre                      8.45                 h9c3ff4c_0    conda-forge
pcre2                     10.37                h032f7d1_0    conda-forge
perl                      5.26.2            h36c2ea0_1008    conda-forge
perl-archive-tar          2.32                    pl526_0    bioconda
perl-carp                 1.38                    pl526_3    bioconda
perl-common-sense         3.74                    pl526_2    bioconda
perl-compress-raw-bzip2   2.087           pl526he1b5a44_0    bioconda
perl-compress-raw-zlib    2.087           pl526hc9558a2_0    bioconda
perl-exporter             5.72                    pl526_1    bioconda
perl-exporter-tiny        1.002001                pl526_0    bioconda
perl-extutils-makemaker   7.36                    pl526_1    bioconda
perl-io-compress          2.087           pl526he1b5a44_0    bioconda
perl-io-zlib              1.10                    pl526_2    bioconda
perl-json                 4.02                    pl526_0    bioconda
perl-json-xs              2.34            pl526h6bb024c_3    bioconda
perl-list-moreutils       0.428                   pl526_1    bioconda
perl-list-moreutils-xs    0.428                   pl526_0    bioconda
perl-pathtools            3.75            pl526h14c3975_1    bioconda
perl-scalar-list-utils    1.52            pl526h516909a_0    bioconda
perl-types-serialiser     1.0                     pl526_2    bioconda
perl-xsloader             0.24                    pl526_0    bioconda
pigz                      2.6                  h27826a3_0    conda-forge
pillow                    8.3.2            py38h8e6f84c_0    conda-forge
pip                       21.2.4             pyhd8ed1ab_0    conda-forge
pixman                    0.40.0               h36c2ea0_0    conda-forge
prodigal                  2.6.3                h779adbc_3    bioconda
pyparsing                 2.4.7              pyh9f0ad1d_0    conda-forge
pyqt                      5.12.3           py38h578d9bd_7    conda-forge
pyqt-impl                 5.12.3           py38h7400c14_7    conda-forge
pyqt5-sip                 4.19.18          py38h709712a_7    conda-forge
pyqtchart                 5.12             py38h7400c14_7    conda-forge
pyqtwebengine             5.12.1           py38h7400c14_7    conda-forge
python                    3.8.12          hb7a2778_0_cpython    conda-forge
python-dateutil           2.8.2              pyhd8ed1ab_0    conda-forge
python_abi                3.8                      2_cp38    conda-forge
qt                        5.12.9               hda022c4_4    conda-forge
r-ape                     5.5               r41h306847c_0    conda-forge
r-base                    4.1.1                hb93adac_1    conda-forge
r-circlize                0.4.13            r41hc72bb7e_0    conda-forge
r-colorspace              2.0_2             r41hcfec24a_0    conda-forge
r-getopt                  1.20.3            r41ha770c72_2    conda-forge
r-globaloptions           0.1.2             r41ha770c72_0    conda-forge
r-lattice                 0.20_44           r41hcfec24a_0    conda-forge
r-nlme                    3.1_153           r41h859d828_0    conda-forge
r-optparse                1.6.6             r41hc72bb7e_1    conda-forge
r-rcpp                    1.0.7             r41h03ef668_0    conda-forge
r-shape                   1.4.6             r41ha770c72_0    conda-forge
readline                  8.1                  h46c0cb4_0    conda-forge
reportlab                 3.5.68           py38hadf75a6_0    conda-forge
scipy                     1.7.1            py38h56a6a73_0    conda-forge
sed                       4.8                  he412f7d_0    conda-forge
setuptools                58.0.4           py38h578d9bd_0    conda-forge
six                       1.16.0             pyh6c4a22f_0    conda-forge
sqlite                    3.36.0               h9cd32fc_1    conda-forge
sysroot_linux-64          2.12                he073ed8_14    conda-forge
tk                        8.6.11               h27826a3_1    conda-forge
tktable                   2.10                 hb7b940f_3    conda-forge
tornado                   6.1              py38h497a2fe_1    conda-forge
wheel                     0.37.0             pyhd8ed1ab_1    conda-forge
xorg-kbproto              1.0.7             h14c3975_1002    conda-forge
xorg-libice               1.0.10               h516909a_0    conda-forge
xorg-libsm                1.2.3             hd9c2040_1000    conda-forge
xorg-libx11               1.7.2                h7f98852_0    conda-forge
xorg-libxau               1.0.9                h14c3975_0    conda-forge
xorg-libxdmcp             1.1.3                h516909a_0    conda-forge
xorg-libxext              1.3.4                h7f98852_1    conda-forge
xorg-libxrender           0.9.10            h7f98852_1003    conda-forge
xorg-libxt                1.2.1                h7f98852_2    conda-forge
xorg-renderproto          0.11.1            h14c3975_1002    conda-forge
xorg-xextproto            7.3.0             h14c3975_1002    conda-forge
xorg-xproto               7.0.31            h14c3975_1007    conda-forge
xz                        5.2.5                h516909a_1    conda-forge
zlib                      1.2.11            h516909a_1010    conda-forge
zstd                      1.5.0                ha95c52a_0    conda-forge
```

Changing `os.mkdir` to `os.makedirs()` should fix the issue:

```
def force_create_folder(folder_to_create):
    if os.path.isdir(folder_to_create):
        shutil.rmtree(folder_to_create, ignore_errors=True)
        if os.path.isdir(folder_to_create):
            shutil.rmtree(folder_to_create, ignore_errors=True)
            if os.path.isdir(folder_to_create):
                shutil.rmtree(folder_to_create, ignore_errors=True)
                if os.path.isdir(folder_to_create):
                    shutil.rmtree(folder_to_create, ignore_errors=True)
    os.mkdir(folder_to_create)
```

btw, what's up with the odd code? Are you running into a latency issue? If yes, it might be better to use a `while` loop with a `sleep` and then `os.path.isdir`?

**Comment by songweizhi** [comment]
Hi Nick,
hi, the output prefix needs to be a continuous text string, not path.
Cheers,
Weizhi

**Comment by songweizhi** [comment]
BTW, you can designate a place for the output files with "-o" with v1.10.6

**Comment by nick-youngblut** [comment]
Thanks. I realized that a little bit ago. I was surprised that the output prefix could not be a path, given that such a constraint was not listed in the script doc, and there was no way to designate an output path (I guess prior to using 1.10.6).

When do you think that the [bioconda recipe](https://bioconda.github.io/recipes/metachip/README.html#package-metachip) will be updated to >=1.10.6?

**Comment by songweizhi** [comment]
I just realized that there is a bioconda recipe for MetaCHIP, and I do have no idea who is helping with that. might be automatically detected/incorporated by bioconda? is it possible for you to install it with pip3?

**Comment by nick-youngblut** [comment]
Actually, it is being auto-bumped: https://github.com/bioconda/bioconda-recipes/pull/30588

**Comment by rpetit3** [comment]
Merged into Bioconda PR, just be available soon

**Comment by susheelbhanu** [comment]
Hey all, the issue seems to still persist. I have the following in my environment: 
```
biopython                 1.78             py38h7b6447c_0    anaconda
```

Here's the error:
```
[2021-11-11 02:04:10] Input genomes grouped into 5 phyla.
[2021-11-11 02:04:11] Total number of qualified genomes for HGT detection: 41.
[2021-11-11 02:04:11] Grouping file exported to: M10_grouping_p5.txt.
[2021-11-11 02:04:11] Running Prodigal for 41 qualified genomes with 18 cores (1-3 minutes pre genome per core).
multiprocessing.pool.RemoteTraceback:
"""
Traceback (most recent call last):
  File "/scratch/users/sbusi/tools/miniconda3/envs/METACHIP/lib/python3.8/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "/scratch/users/sbusi/tools/miniconda3/envs/METACHIP/lib/python3.8/multiprocessing/pool.py", line 48, in mapstar
    return list(map(*args))
  File "/scratch/users/sbusi/tools/miniconda3/envs/METACHIP/lib/python3.8/site-packages/MetaCHIP/PI.py", line 234, in prodigal_worker
    prodigal_parser(pwd_input_genome, pwd_output_sco, input_genome_basename, pwd_prodigal_output_folder)
  File "/scratch/users/sbusi/tools/miniconda3/envs/METACHIP/lib/python3.8/site-packages/MetaCHIP/PI.py", line 203, in prodigal_parser
    SeqIO.write(current_SeqRecord, bin_gbk_file_handle, 'genbank')
  File "/home/users/sbusi/.local/lib/python3.8/site-packages/Bio/SeqIO/__init__.py", line 531, in write
    count = writer_class(handle).write_file(sequences)
  File "/home/users/sbusi/.local/lib/python3.8/site-packages/Bio/SeqIO/Interfaces.py", line 235, in write_file
    count = self.write_records(records, maxcount)
  File "/home/users/sbusi/.local/lib/python3.8/site-packages/Bio/SeqIO/Interfaces.py", line 209, in write_records
    self.write_record(record)
  File "/home/users/sbusi/.local/lib/python3.8/site-packages/Bio/SeqIO/InsdcIO.py", line 1005, in write_record
    self._write_the_first_line(record)
  File "/home/users/sbusi/.local/lib/python3.8/site-packages/Bio/SeqIO/InsdcIO.py", line 757, in _write_the_first_line
    raise ValueError("Need a Nucleotide or Protein alphabet")
ValueError: Need a Nucleotide or Protein alphabet
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/scratch/users/sbusi/tools/miniconda3/envs/METACHIP/bin/MetaCHIP", line 166, in <module>
    PI(args, MetaCHIP_config.config_dict)
  File "/scratch/users/sbusi/tools/miniconda3/envs/METACHIP/lib/python3.8/site-packages/MetaCHIP/PI.py", line 875, in PI
    pool.map(prodigal_worker, list_for_multiple_arguments_Prodigal)
  File "/scratch/users/sbusi/tools/miniconda3/envs/METACHIP/lib/python3.8/multiprocessing/pool.py", line 364, in map
    return self._map_async(func, iterable, mapstar, chunksize).get()
  File "/scratch/users/sbusi/tools/miniconda3/envs/METACHIP/lib/python3.8/multiprocessing/pool.py", line 771, in get
    raise self._value
ValueError: Need a Nucleotide or Protein alphabet
```

**Comment by susheelbhanu** [comment]
Attached is the conda environment I'm attaching. 
[metachip.yaml.txt](https://github.com/songweizhi/MetaCHIP/files/7518821/metachip.yaml.txt)

Thank you!

**Comment by ChaoLab** [comment]
@susheelbhanu Hi, I have the same error report as yours. Did you figure out how to solve this?

**Comment by ChaoLab** [comment]
@susheelbhanu @songweizhi It does not solve my problem by setting core numbers. I guess it is because I have "NNNN"s in my input genomes. For example, some faa and fnn files only have 14 lines after prodigal annotation. I think it must be something wrong with this. I tried to change this
![image](https://user-images.githubusercontent.com/35715202/184243893-5feb1c9b-9df8-47ab-9f0a-fbbe544f3690.png)

, but it does not help

**Comment by susheelbhanu** [comment]
I suppose that could do it. Have you tried modifying your multifasta file to remove any empty spaces or newlines?

**Comment by ChaoLab** [comment]
@susheelbhanu Hi, today I tried breaking scaffold with multiple Ns. I still got the same error report. Do you know where is the problem? Here is a screenshot of my input fasta file:

![image](https://user-images.githubusercontent.com/35715202/184466088-588a3658-578a-48d0-a17a-94cc9de2f91a.png)

I named ..._1 ..._2 after breaking the scaffold with multiple Ns

**Comment by songweizhi** [comment]
Hi Chao,
can you please share with me your input file so I can take a look at this issue? your file will only be used for debugging.
Thanks,
Weizhi

**Comment by ChaoLab** [comment]
Upgrading biopython to version 1.79 solves this issue
