### ISSUE TITLE
Index out of range

### ISSUE THREAD

**Issue by susheelbhanu** [songweizhi/MetaCHIP#26]
Hi @songweizhi 

I'm trying to run `MetaCHIP` and getting the following error:

```
Activating conda environment: /scratch/users/sbusi/tools/miniconda3/envs/snakemake/pipeline/c9e7ba4a44b9d0d2baa8ed458e82adc8
Thu Nov 11 01:08:12 CET 2021
MetaCHIP working directory detected, program exited!
Traceback (most recent call last):
  File "/scratch/users/sbusi/tools/miniconda3/envs/snakemake/pipeline/c9e7ba4a44b9d0d2baa8ed458e82adc8/bin/MetaCHIP", line 169, in <module>
    BP(args, MetaCHIP_config.config_dict)
  File "/scratch/users/sbusi/tools/miniconda3/envs/snakemake/pipeline/c9e7ba4a44b9d0d2baa8ed458e82adc8/lib/python3.8/site-packages/MetaCHIP/BP.py", line 1737, in BP
    pwd_prodigal_output_folder_detected    = [os.path.basename(file_name) for file_name in glob.glob(pwd_prodigal_output_folder_re)][0]
IndexError: list index out of range
```

I'm running it inside a snakemake workflow and the rule looks like so:
```
rule metachip:
    input: /work/projects/amrwd/mice_amr_2021/fastq/IMP3/metachip/M11, /work/projects/amrwd/mice_amr_2021/fastq/IMP3/metachip/M11/gtdbtk_output/M11_gtdbtk.tsv
    output: /work/projects/amrwd/mice_amr_2021/fastq/IMP3/metachip/M11_MetaCHIP_wd/M11_all_blastn_commands.txt
    jobid: 0
    wildcards: datadir=/work/projects/amrwd/mice_amr_2021/fastq/IMP3/metachip, sample=M11
    threads: 18
    resources: mem_mb=1000, disk_mb=1000, tmpdir=/tmp

        date &&
        export PATH=$PATH:/home/users/sbusi/apps/metachip/bin && export PATH=$PATH:/scratch/users/sbusi/tools/miniconda3/envs/anvio-7/bin &&
        MetaCHIP PI -p M11 -r g -t 18 -i /work/projects/amrwd/mice_amr_2021/fastq/IMP3/metachip/M11 -x fa -taxon /work/projects/amrwd/mice_amr_2021/fastq/IMP3/metachip/M11/gtdbtk_output/M11_gtdbtk.tsv -o $(dirname /work/projects/amrwd/mice_amr_2021/fastq/IMP3/metachip/M11_MetaCHIP_wd/M11_all_blastn_commands.txt) &&
        MetaCHIP BP -p M11 -r g -t 18 -o $(dirname /work/projects/amrwd/mice_amr_2021/fastq/IMP3/metachip/M11_MetaCHIP_wd/M11_all_blastn_commands.txt) -force &&
        date
```

Thank you for your help!

**Comment by songweizhi** [comment]
Hi susheelbhanu,

Thanks for using MetaCHIP, could you please update MetaCHIP to version 1.10.8 and see if you can bypass the error.

Cheers,
Weizhi

**Comment by susheelbhanu** [comment]
Thanks @songweizhi. Was using `1.10.6`, so will retry with the updated environment. 

Will keep you posted!

**Comment by susheelbhanu** [comment]
Hey @songweizhi the problem seems to persist. See below please
```
Thu Nov 18 13:19:58 CET 2021
[2021-11-18 13:20:13] Input genomes grouped into 29 genera.
[2021-11-18 13:20:14] Ignored 10 genome(s) for genus level HGT detection (unknown genus assignment).
[2021-11-18 13:20:14] Total number of qualified genomes for HGT detection: 90.
[2021-11-18 13:20:15] Grouping file exported to: M7_grouping_g29.txt.
[2021-11-18 13:20:15] Running Prodigal for 90 qualified genomes with 8 cores (1-3 minutes per genome per core).
multiprocessing.pool.RemoteTraceback:
"""
Traceback (most recent call last):
  File "/scratch/users/sbusi/tools/miniconda3/envs/snakemake/pipeline/9bdb880e3c8c91ddcdd690807ef6f3d0/lib/python3.8/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "/scratch/users/sbusi/tools/miniconda3/envs/snakemake/pipeline/9bdb880e3c8c91ddcdd690807ef6f3d0/lib/python3.8/multiprocessing/pool.py", line 48, in mapstar
    return list(map(*args))
  File "/scratch/users/sbusi/tools/miniconda3/envs/snakemake/pipeline/9bdb880e3c8c91ddcdd690807ef6f3d0/lib/python3.8/site-packages/MetaCHIP/PI.py", line 238, in prodigal_worker
    prodigal_parser(pwd_input_genome, pwd_output_sco, input_genome_basename, pwd_prodigal_output_folder)
  File "/scratch/users/sbusi/tools/miniconda3/envs/snakemake/pipeline/9bdb880e3c8c91ddcdd690807ef6f3d0/lib/python3.8/site-packages/MetaCHIP/PI.py", line 207, in prodigal_parser
    SeqIO.write(current_SeqRecord, bin_gbk_file_handle, 'genbank')
  File "/home/users/sbusi/.local/lib/python3.8/site-packages/Bio/SeqIO/__init__.py", line 531, in write
    count = writer_class(handle).write_file(sequences)
  File "/home/users/sbusi/.local/lib/python3.8/site-packages/Bio/SeqIO/Interfaces.py", line 235, in write_file
    count = self.write_records(records, maxcount)
  File "/home/users/sbusi/.local/lib/python3.8/site-packages/Bio/SeqIO/Interfaces.py", line 209, in write_records
    self.write_record(record)
  File "/home/users/sbusi/.local/lib/python3.8/site-packages/Bio/SeqIO/InsdcIO.py", line 1005, in write_record
    self._write_the_first_line(record)
  File "/home/users/sbusi/.local/lib/python3.8/site-packages/Bio/SeqIO/InsdcIO.py", line 757, in _write_the_first_line
    raise ValueError("Need a Nucleotide or Protein alphabet")
ValueError: Need a Nucleotide or Protein alphabet
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/scratch/users/sbusi/tools/miniconda3/envs/snakemake/pipeline/9bdb880e3c8c91ddcdd690807ef6f3d0/bin/MetaCHIP", line 166, in <module>
    PI(args, MetaCHIP_config.config_dict)
  File "/scratch/users/sbusi/tools/miniconda3/envs/snakemake/pipeline/9bdb880e3c8c91ddcdd690807ef6f3d0/lib/python3.8/site-packages/MetaCHIP/PI.py", line 879, in PI
    pool.map(prodigal_worker, list_for_multiple_arguments_Prodigal)
  File "/scratch/users/sbusi/tools/miniconda3/envs/snakemake/pipeline/9bdb880e3c8c91ddcdd690807ef6f3d0/lib/python3.8/multiprocessing/pool.py", line 364, in map
    return self._map_async(func, iterable, mapstar, chunksize).get()
  File "/scratch/users/sbusi/tools/miniconda3/envs/snakemake/pipeline/9bdb880e3c8c91ddcdd690807ef6f3d0/lib/python3.8/multiprocessing/pool.py", line 771, in get
    raise self._value
ValueError: Need a Nucleotide or Protein alphabet
```

I have this in my conda environment:
```
  - pip:
    - metachip==1.10.8
   ```

**Comment by songweizhi** [comment]
Can you please check your version of biopython with:

    import Bio
    print(Bio.__version__)

It needs to be higher than 1.78, I didn't see an error with 1.7.9.

**Comment by susheelbhanu** [comment]
I have `- biopython=1.78`.. Will switch and check!

**Comment by songweizhi** [comment]
that's weird. not sure if I am correct, but seems that the error message "Need a Nucleotide or Protein alphabet" can only be found in biopython with version <=1.77. there is no such error report in biopython with version >= 1.78.

**Comment by susheelbhanu** [comment]
Ok, the issue seems to persist. I'm attaching the environment I'm using. Could you please see if anything stands out? 
Thank you! 

[metachip_test.yaml.txt](https://github.com/songweizhi/MetaCHIP/files/7563619/metachip_test.yaml.txt)

**Comment by susheelbhanu** [comment]
Update: With the above `conda env`, the previous error goes away but I get another error:
```
Adding sequences from FASTA; added 96940 sequences in 3.7085 seconds.
[2021-11-18 15:56:30] Get SCG tree: concatenating alignments.
[2021-11-18 15:56:30] Get SCG tree: removing columns from concatenated alignment represented by <50% of genomes and with amino acid consensus <25%.
[2021-11-18 15:56:31] Get SCG tree: running FastTree.
[2021-11-18 15:57:00] SCG tree exported to: M13_g_SCG_tree.newick.
[2021-11-18 15:57:00] Making blast database.
[2021-11-18 15:57:04] Blastn commands exported to: M13_g_blastn_commands.txt.
[2021-11-18 15:57:04] Running blastn for 46 qualified genomes with 8 cores.
[2021-11-18 16:05:58] Blast results exported to: /work/projects/amrwd/mice_amr_2021/fastq/IMP3/metachip/M13_MetaCHIP_wd/tmp/M13_g_blastn_results.
[2021-11-18 16:05:58] PI step done!
[2021-11-18 16:05:59] Filtering blastn results with the following criteria: Query genome != Subject genome, Alignment length >= 200bp and coverage >= 75%.
[2021-11-18 16:06:00] Detect HGT among genera: input genomes were clustered into 27 genera.
[2021-11-18 16:06:00] Detect HGT among genera: Best-match approach.
[2021-11-18 16:06:00] Detect HGT among genera: get group-to-group identities with 8 cores.
[2021-11-18 16:06:02] Detect HGT among genera: analyzing Blast hits with 8 cores.
[2021-11-18 16:06:03] Detect HGT among genera: plotting flanking regions with 8 cores.
Command line argument error: Argument "subject". File is not accessible:  `/work/projects/amrwd/mice_amr_2021/fastq/IMP3/metachip/M13_MetaCHIP_wd/tmp/M13_HGT_ip90_al200bp_c75_ei80_f10kbp_g27/M13_g27_Flanking_region_plots/M13day0MG_G18.2.contigs_00803___M13day0MG_maxbin_res.015.fasta_sub.contigs_00100/M13day0MG_maxbin_res.015.fasta_sub.contigs_00100_10000bp.fasta'
Command line argument error: Argument "subject". File is not accessible:  `/work/projects/amrwd/mice_amr_2021/fastq/IMP3/metachip/M13_MetaCHIP_wd/tmp/M13_HGT_ip90_al200bp_c75_ei80_f10kbp_g27/M13_g27_Flanking_region_plots/M13day0MG_G18.2.contigs_00803___M13day0MG_maxbin_res.015.fasta_sub.contigs_00100/M13day0MG_maxbin_res.015.fasta_sub.contigs_00100.fasta'
```

**Comment by songweizhi** [comment]
Can you please refer to issue #12 and #13 for a possible solution?
Weizhi

**Comment by susheelbhanu** [comment]
Thank you!
