### ISSUE TITLE
Error in PI step: Invalid index

### ISSUE THREAD

**Issue by linshutian02** [songweizhi/MetaCHIP#29]
Hi
   Few days ago, I downloaded the MetaCHIP(V1.10.9) and succeeded in testing the example data. But when I run MetaCHIP with the data myself, the error occur below: 
  
   command: MetaCHIP PI -p sample_3 -r c -t 6 -i sample_3_bins -x fasta -taxon sample_3_bins_GTDB.tsv
   
[2022-01-13 22:57:18] Input genomes grouped into 3 classes.
[2022-01-13 22:57:18] Total number of qualified genomes for HGT detection: 10.
[2022-01-13 22:57:19] Grouping file exported to: sample_3_grouping_c3.txt.
[2022-01-13 22:57:19] Running Prodigal for 10 qualified genomes with 6 cores (1-3 minutes per genome per core).
[2022-01-13 22:57:28] Get SCG tree: running hmmsearch with 6 cores.
[2022-01-13 22:57:30] Get SCG tree: running hmmalign with 6 cores.

Error: File existence/permissions problem in trying to open HMM file sample_3_MetaCHIP_wd/sample_3_c_get_SCG_tree_wd/sample_3_c_hmm_profile_fetched/.hmm.
HMM file sample_3_MetaCHIP_wd/sample_3_c_get_SCG_tree_wd/sample_3_c_hmm_profile_fetched/.hmm not found (nor an .h3m binary of i

[2022-01-13 22:57:35] Get SCG tree: concatenating alignments.
[2022-01-13 22:57:35] Get SCG tree: removing columns from concatenated alignment represented by <50% of genomes and with amino acid consensus <25%.
Traceback (most recent call last):
  File "/ldfssz1/ST_META/share/User/juyanmei/miniconda3/bin/MetaCHIP", line 166, in <module>
    PI(args, MetaCHIP_config.config_dict)
  File "/ldfssz1/ST_META/share/User/juyanmei/miniconda3/lib/python3.7/site-packages/MetaCHIP/PI.py", line 974, in PI
    remove_low_cov_and_consensus_columns(pwd_combined_alignment_file_tmp, minimal_cov_in_msa, min_consensus_in_msa, pwd_combined_alignment_file)
  File "/ldfssz1/ST_META/share/User/juyanmei/miniconda3/lib/python3.7/site-packages/MetaCHIP/PI.py", line 533, in remove_low_cov_and_consensus_columns
    alignment_cov = remove_low_cov_columns(alignment, minimal_cov)
  File "/ldfssz1/ST_META/share/User/juyanmei/miniconda3/lib/python3.7/site-packages/MetaCHIP/PI.py", line 492, in remove_low_cov_columns
    alignment_new = remove_columns_from_msa(alignment_in, low_cov_columns)
  File "/ldfssz1/ST_META/share/User/juyanmei/miniconda3/lib/python3.7/site-packages/MetaCHIP/PI.py", line 460, in remove_columns_from_msa
    segment_value = alignment_in[:, segment[0]]
  File "/ldfssz1/ST_META/share/User/juyanmei/miniconda3/lib/python3.7/site-packages/Bio/Align/__init__.py", line 760, in __getitem__
    rec[col_index] for rec in self._records[row_index]
  File "/ldfssz1/ST_META/share/User/juyanmei/miniconda3/lib/python3.7/site-packages/Bio/Align/__init__.py", line 160, in __init__
    self.extend(records)
  File "/ldfssz1/ST_META/share/User/juyanmei/miniconda3/lib/python3.7/site-packages/Bio/Align/__init__.py", line 450, in extend
    rec = next(records)
  File "/ldfssz1/ST_META/share/User/juyanmei/miniconda3/lib/python3.7/site-packages/Bio/Align/__init__.py", line 760, in <genexpr>
    rec[col_index] for rec in self._records[row_index]
  File "/ldfssz1/ST_META/share/User/juyanmei/miniconda3/lib/python3.7/site-packages/Bio/SeqRecord.py", line 519, in __getitem__
    raise ValueError("Invalid index")
ValueError: Invalid index

   By the way, the version of biopython is V1.79. 
   What's wrong with it?

**Comment by bahiyahazli** [comment]
Hello! I received the same error too! I have 2 sample groups and both return the same error.

I do not know whether the problem is due to `Error: File existence/permissions problem in trying to open HMM file sample_3_MetaCHIP_wd/sample_3_c_get_SCG_tree_wd/sample_3_c_hmm_profile_fetched/.hmm.
HMM file sample_3_MetaCHIP_wd/sample_3_c_get_SCG_tree_wd/sample_3_c_hmm_profile_fetched/.hmm not found` that causes the next step to have an invalid index, or something else.

Have you perhaps found a solution for this error? 

Thanks
