### ISSUE TITLE
IndexError: list index out of range when MetaCHIP=1.10.9 & biopython=1.79

### ISSUE THREAD

**Issue by yuqingyi33** [songweizhi/MetaCHIP#32]
Dear doctor song @ songweizhi:
 I am running MetaCHIP for this command:
MetaCHIP BP -p AN20.MetaCHIP -r g -t 100
My  MetaCHIP version is 1.10.9 and my biopython version is 1.79.
But i still met this error: 
MetaCHIP BP -p AN20.MetaCHIP -r g -t 100
[2022-04-15 21:26:08] Filtered blastn results detected, filtration step skipped.
[2022-04-15 21:26:08] Detect HGT among genera: input genomes were clustered into 28 genera.
[2022-04-15 21:26:09] Detect HGT among genera: Best-match approach.
[2022-04-15 21:26:09] Detect HGT among genera: get group-to-group identities with 100 cores.
[2022-04-15 21:26:11] Detect HGT among genera: analyzing Blast hits with 100 cores.
multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/ifs1/User/wangc/anaconda3/envs/MetaCHIP3/lib/python3.7/multiprocessing/pool.py", line 121, in worker
    result = (True, func(*args, **kwds))
  File "/ifs1/User/wangc/anaconda3/envs/MetaCHIP3/lib/python3.7/multiprocessing/pool.py", line 44, in mapstar
    return list(map(*args))
  File "/ifs1/User/wangc/anaconda3/envs/MetaCHIP3/lib/python3.7/site-packages/MetaCHIP/BP.py", line 409, in get_HGT_worker
    group_pair_iden_cutoff_dict)
  File "/ifs1/User/wangc/anaconda3/envs/MetaCHIP3/lib/python3.7/site-packages/MetaCHIP/BP.py", line 226, in get_candidates
    query_gene_name = query_split[1]
IndexError: list index out of range
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/ifs1/User/wangc/anaconda3/envs/MetaCHIP3/bin/MetaCHIP", line 169, in <module>
    BP(args, MetaCHIP_config.config_dict)
  File "/ifs1/User/wangc/anaconda3/envs/MetaCHIP3/lib/python3.7/site-packages/MetaCHIP/BP.py", line 2115, in BP
    pool.map(get_HGT_worker, list_for_multiple_arguments_get_HGT)
  File "/ifs1/User/wangc/anaconda3/envs/MetaCHIP3/lib/python3.7/multiprocessing/pool.py", line 268, in map
    return self._map_async(func, iterable, mapstar, chunksize).get()
  File "/ifs1/User/wangc/anaconda3/envs/MetaCHIP3/lib/python3.7/multiprocessing/pool.py", line 657, in get
    raise self._value
IndexError: list index out of range

It is amazing that my other treatments can run this command successfully but except this one.
Please tell me how to solve this problems, I am looking forward to your reply
Thank you very much!

**Comment by songweizhi** [comment]
can you please refer to #12 for a potential solution, please let me know if the error still exists.

**Comment by yuqingyi33** [comment]
Dear doctor song @ songweizhi:
I refered #12 and I haven shorted the genome name, but I am sorry that the problems is still existing.
Interestingly, this error may occur just at genus level and the error information is as follows:
$MetaCHIP PI -p AN20.MetaCHIP5 -r pcofg -t 150 -i AN20_dreped_genomes -x fa -taxon AN20_goodbin.gtdbtk.classification.tsv
[2022-04-17 20:25:44] Input genomes grouped into 9 phyla.
[2022-04-17 20:25:45] Input genomes grouped into 12 classes.
[2022-04-17 20:25:45] Input genomes grouped into 20 orders.
[2022-04-17 20:25:46] Input genomes grouped into 26 families.
[2022-04-17 20:25:46] Ignored 3 genome(s) for family level HGT detection (unknown family assignment).
[2022-04-17 20:25:47] Input genomes grouped into 28 genera.
[2022-04-17 20:25:47] Ignored 17 genome(s) for genus level HGT detection (unknown genus assignment).
[2022-04-17 20:25:48] Total number of qualified genomes for HGT detection: 52.
[2022-04-17 20:25:48] Grouping file exported to: AN20.MetaCHIP5_grouping_p9.txt.
[2022-04-17 20:25:49] Grouping file exported to: AN20.MetaCHIP5_grouping_c12.txt.
[2022-04-17 20:25:49] Grouping file exported to: AN20.MetaCHIP5_grouping_o20.txt.
[2022-04-17 20:25:50] Grouping file exported to: AN20.MetaCHIP5_grouping_f26.txt.
[2022-04-17 20:25:50] Grouping file exported to: AN20.MetaCHIP5_grouping_g28.txt.
[2022-04-17 20:25:50] Running Prodigal for 52 qualified genomes with 150 cores (1-3 minutes per genome per core).
[2022-04-17 20:26:24] Get SCG tree: running hmmsearch with 150 cores.
[2022-04-17 20:26:25] Get SCG tree: running hmmalign with 150 cores.
[2022-04-17 20:26:27] Get SCG tree: concatenating alignments.
[2022-04-17 20:26:27] Get SCG tree: removing columns from concatenated alignment represented by <50% of genomes and with amino acid consensus <25%.
[2022-04-17 20:26:28] Get SCG tree: running FastTree.
[2022-04-17 20:26:44] SCG tree exported to: AN20.MetaCHIP5_pcofg_SCG_tree.newick.                                       
[2022-04-17 20:26:44] Making blast database.
Building a new DB, current time: 04/17/2022 20:26:45
New DB name:   /ifs1/User/wangc/YuQY/fishdata/all_reads/AN20_all_reads_binned_quanted_refinied/AN20.bin/AN20.refinement/AN20.MetaCHIP5_MetaCHIP_wd/AN20.MetaCHIP5_pcofg_blastdb/AN20.MetaCHIP5_pcofg_combined_ffn.fasta
New DB title:  AN20.MetaCHIP5_MetaCHIP_wd/AN20.MetaCHIP5_pcofg_blastdb/AN20.MetaCHIP5_pcofg_combined_ffn.fasta
Sequence type: Nucleotide
Keep MBits: T
Maximum file size: 1000000000B
Adding sequences from FASTA; added 138751 sequences in 2.48495 seconds.

[2022-04-17 20:26:49] Blastn commands exported to: AN20.MetaCHIP5_pcofg_blastn_commands.txt.
[2022-04-17 20:26:49] Running blastn for 52 qualified genomes with 150 cores.
[2022-04-17 20:50:41] Blast results exported to: AN20.MetaCHIP5_MetaCHIP_wd/AN20.MetaCHIP5_pcofg_blastn_results.
[2022-04-17 20:50:41] PI step done!

$ MetaCHIP BP -p AN20.MetaCHIP5 -r g -t 150
[2022-04-17 20:51:38] Filtering blastn results with the following criteria: Query genome != Subject genome, Alignment length >= 200bp and coverage >= 75%.
[2022-04-17 20:51:39] Detect HGT among genera: input genomes were clustered into 28 genera.
[2022-04-17 20:51:39] Detect HGT among genera: Best-match approach.
[2022-04-17 20:51:39] Detect HGT among genera: get group-to-group identities with 150 cores.
[2022-04-17 20:51:40] Detect HGT among genera: analyzing Blast hits with 150 cores.
multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/ifs1/User/wangc/anaconda3/envs/MetaCHIP3/lib/python3.7/multiprocessing/pool.py", line 121, in worker
    result = (True, func(*args, **kwds))
  File "/ifs1/User/wangc/anaconda3/envs/MetaCHIP3/lib/python3.7/multiprocessing/pool.py", line 44, in mapstar
    return list(map(*args))
  File "/ifs1/User/wangc/anaconda3/envs/MetaCHIP3/lib/python3.7/site-packages/MetaCHIP/BP.py", line 409, in get_HGT_worker
    group_pair_iden_cutoff_dict)
  File "/ifs1/User/wangc/anaconda3/envs/MetaCHIP3/lib/python3.7/site-packages/MetaCHIP/BP.py", line 226, in get_candidates
    query_gene_name = query_split[1]
IndexError: list index out of range
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/ifs1/User/wangc/anaconda3/envs/MetaCHIP3/bin/MetaCHIP", line 169, in <module>
    BP(args, MetaCHIP_config.config_dict)
  File "/ifs1/User/wangc/anaconda3/envs/MetaCHIP3/lib/python3.7/site-packages/MetaCHIP/BP.py", line 2115, in BP
    pool.map(get_HGT_worker, list_for_multiple_arguments_get_HGT)
  File "/ifs1/User/wangc/anaconda3/envs/MetaCHIP3/lib/python3.7/multiprocessing/pool.py", line 268, in map
    return self._map_async(func, iterable, mapstar, chunksize).get()
  File "/ifs1/User/wangc/anaconda3/envs/MetaCHIP3/lib/python3.7/multiprocessing/pool.py", line 657, in get
    raise self._value
IndexError: list index out of range

Please let me now where i am wrong. Looking forward to your reply.
Thank you very much.

**Comment by songweizhi** [comment]
Dear yuqingyi33,
I am very sorry for the late reply, I just got a chance to look at this now. I couldn't reprocude this error with a demo dataset, If you still need to run MetaCHIP, is it possible to share with me your input files to metaCHIP? your files will be used for debugging only.
Weizhi
