### ISSUE TITLE
MetaCHIP report errors

### ISSUE THREAD

**Issue by LiZhihua1982** [songweizhi/MetaCHIP#7]
![image](https://user-images.githubusercontent.com/38903973/85187507-06ce8080-b2db-11ea-9120-4c270e7eccd0.png)

**Comment by susheelbhanu** [comment]
Hey @songweizhi 

I ran METACHIP successfully 2 months ago, but now I'm running into the issue below again:
```
[2020-08-11 10:47:35] Input genomes clustered into 0 groups
[2020-08-11 10:47:36] Grouping file exported to: C009_g0_grouping.txt
[2020-08-11 10:47:36] Calculating the size of input genomes
[2020-08-11 10:47:40] The size of input genomes exported to: C009_all_genome_size.txt
[2020-08-11 10:47:40] Running Prodigal with 16 cores for all input genomes
[2020-08-11 10:49:34] Copying annotation files of qualified genomes to corresponding folders
[2020-08-11 10:49:34] Running Hmmsearch with 16 cores
[2020-08-11 10:49:34] Running Hmmalign with 16 cores
[2020-08-11 10:49:36] Concatenating alignments
[2020-08-11 10:49:36] Removing columns from concatenated alignment represented by <50% of genomes and with an amino acid consensus <25%
Traceback (most recent call last):
  File "/home/users/sbusi/apps/miniconda3/envs/METACHIP/bin/MetaCHIP", line 211, in <module>
    PI(args, config_dict)
  File "/home/users/sbusi/apps/miniconda3/envs/METACHIP/lib/python3.8/site-packages/MetaCHIP/PI.py", line 1197, in PI
    remove_low_cov_and_consensus_columns(pwd_combined_alignment_file_tmp, minimal_cov_in_msa, min_consensus_in_msa, pwd_combined_alignment_file)
  File "/home/users/sbusi/apps/miniconda3/envs/METACHIP/lib/python3.8/site-packages/MetaCHIP/PI.py", line 278, in remove_low_cov_and_consensus_columns
    alignment = AlignIO.read(alignment_file_in, "fasta")
  File "/home/users/sbusi/apps/miniconda3/envs/METACHIP/lib/python3.8/site-packages/Bio/AlignIO/__init__.py", line 451, in read
    raise ValueError("No records found in handle")
ValueError: No records found in handle
[2020-08-11 10:49:37] Found grouping file C009_g0_grouping.txt, input genomes were clustered into 0 groups
[2020-08-11 10:49:37] Filtering blast matches with the following criteria: Query genome != Subject genome, Alignment length >= 200bp and coverage >= 75%
[2020-08-11 10:49:37] No blast results detected, program exited!
== Ending run at Tue Aug 11 10:49:37 CEST 2020
```

Any pointers where it's going wrong?
Thank you!

**Comment by susheelbhanu** [comment]
@LiZhihua1982 and @songweizhi 
This issue is resolved. I found that names of the bins in my "sample_gtdbtk.tsv" file had the `.fa` extension to them, which was causing the issue. 

Example: `bad file`
```
user_genome     classification  fastani_reference       fastani_reference_radius        fastani_taxonomy        fastani_ani     fastani_af      closest_placement_reference     closest_placement_taxonomy      closest_placement_ani   closest_placement_af    pplacer_taxonomy        classification_method   note    other_related_references(genome_id,species_name,radius,ANI,AF)      aa_percent      translation_table       red_value       warnings
V3_maxbin_res.007.fasta_sub.contigs.fa     d__Bacteria;p__Firmicutes;c__Bacilli;o__Lactobacillales;f__Enterococcaceae;g__Enterococcus;s__Enterococcus faecalis     GCF_000392875.1 95.0    d__Bacteria;p__Firmicutes;c__Bacilli;o__Lactobacillales;f__Enterococcaceae;g__Enterococcus;s__Enterococcus faecalis     98.45   0.82    GCF_000392875.1 d__Bacteria;p__Firmicutes;c__Bacilli;o__Lactobacillales;f__Enterococcaceae;g__Enterococcus;s__Enterococcus faecalis 98.45   0.82    d__Bacteria;p__Firmicutes;c__Bacilli;o__Lactobacillales;f__Enterococcaceae;g__Enterococcus;s__  ANI/Placement   topological placement and ANI have congruent species assignments        N/A     61.31   11      N/A     Genome has more than 14.2% of markers with multiple hits
V3_maxbin_res.003.fasta_sub.contigs.fa     d__Bacteria;p__Bacteroidota;c__Bacteroidia;o__Bacteroidales;f__Bacteroidaceae;g__Bacteroides_B;s__Bacteroides_B vulgatus        GCF_000012825.1 95.35   d__Bacteria;p__Bacteroidota;c__Bacteroidia;o__Bacteroidales;f__Bacteroidaceae;g__Bacteroides_B;s__Bacteroides_B vulgatus        98.92   0.86    GCF_000012825.1 d__Bacteria;p__Bacteroidota;c__Bacteroidia;o__Bacteroidales;f__Bacteroidaceae;g__Bacteroides_B;s__Bacteroides_B vulgatus    98.92   0.86    d__Bacteria;p__Bacteroidota;c__Bacteroidia;o__Bacteroidales;f__Bacteroidaceae;g__Bacteroides_B;s__      ANI/Placement   topological placement and ANI have congruent species assignments        GCF_000156075.1, s__Bacteroides_B dorei, 95.35, 95.55, 0.83; GCA_000614185.1, s__Bacteroides_B sartorii, 95.0, 90.3, 0.7; GCF_000382445.1, s__Bacteroides_B massiliensis, 95.0, 81.85, 0.4; GCA_002493165.1, s__Bacteroides_B sp002493165, 95.0, 80.38, 0.41        98.77   11      N/A     N/A
```

`Good file`
```
user_genome     classification  fastani_reference       fastani_reference_radius        fastani_taxonomy        fastani_ani     fastani_af      closest_placement_reference     closest_placement_taxonomy      closest_placement_ani   closest_placement_af    pplacer_taxonomy        classification_method   note    other_related_references(genome_id,species_name,radius,ANI,AF)      aa_percent      translation_table       red_value       warnings
V3_maxbin_res.007.fasta_sub.contigs     d__Bacteria;p__Firmicutes;c__Bacilli;o__Lactobacillales;f__Enterococcaceae;g__Enterococcus;s__Enterococcus faecalis     GCF_000392875.1 95.0    d__Bacteria;p__Firmicutes;c__Bacilli;o__Lactobacillales;f__Enterococcaceae;g__Enterococcus;s__Enterococcus faecalis     98.45   0.82    GCF_000392875.1 d__Bacteria;p__Firmicutes;c__Bacilli;o__Lactobacillales;f__Enterococcaceae;g__Enterococcus;s__Enterococcus faecalis 98.45   0.82    d__Bacteria;p__Firmicutes;c__Bacilli;o__Lactobacillales;f__Enterococcaceae;g__Enterococcus;s__  ANI/Placement   topological placement and ANI have congruent species assignments        N/A     61.31   11      N/A     Genome has more than 14.2% of markers with multiple hits
V3_maxbin_res.003.fasta_sub.contigs     d__Bacteria;p__Bacteroidota;c__Bacteroidia;o__Bacteroidales;f__Bacteroidaceae;g__Bacteroides_B;s__Bacteroides_B vulgatus        GCF_000012825.1 95.35   d__Bacteria;p__Bacteroidota;c__Bacteroidia;o__Bacteroidales;f__Bacteroidaceae;g__Bacteroides_B;s__Bacteroides_B vulgatus        98.92   0.86    GCF_000012825.1 d__Bacteria;p__Bacteroidota;c__Bacteroidia;o__Bacteroidales;f__Bacteroidaceae;g__Bacteroides_B;s__Bacteroides_B vulgatus    98.92   0.86    d__Bacteria;p__Bacteroidota;c__Bacteroidia;o__Bacteroidales;f__Bacteroidaceae;g__Bacteroides_B;s__      ANI/Placement   topological placement and ANI have congruent species assignments        GCF_000156075.1, s__Bacteroides_B dorei, 95.35, 95.55, 0.83; GCA_000614185.1, s__Bacteroides_B sartorii, 95.0, 90.3, 0.7; GCF_000382445.1, s__Bacteroides_B massiliensis, 95.0, 81.85, 0.4; GCA_002493165.1, s__Bacteroides_B sp002493165, 95.0, 80.38, 0.41        98.77   11      N/A     N/A
```

As long as the `.fa` extension is removed in the `gtdbtk.tsv` file, everything runs smoothly!

Please check your files as well. Best!

**Comment by songweizhi** [comment]
Hi susheelbhanu, 
Thanks for your suggestion, I 'll look over it this weekend. 
Weizhi

**Comment by susheelbhanu** [comment]
Thanks @songweizhi. Maybe adding it in the description or usage instructions will be helpful for the future as well. Best!

**Comment by songweizhi** [comment]
Thanks susheelbhanu, a description regarding this issue has been added to the instruction for the taxonomy file.
Weizhi
