### ISSUE TITLE
Index out of range error in MetaCHIP BP

### ISSUE THREAD

**Issue by surh** [songweizhi/MetaCHIP#8]
I am trying to run MetaCHIP on 42 genomes. I am able to run the PI portion of the pipeline either using either GTDBtk or a custom grouping, however, the second step fails with an error about an index out of range. Here is the full output:

```bash
$ MetaCHIP BP -p taxonomy -r g -t 48
[2020-06-22 20:32:21] Found grouping file taxonomy_g9_grouping.txt, input genomes were clustered into 9 groups
[2020-06-22 20:32:21] Filtering blast matches with the following criteria: Query genome != Subject genome, Alignment length >= 200bp and coverage >= 75%
[2020-06-22 20:32:22] Combining filtered blastn results
[2020-06-22 20:32:22] Get group-to-group identities with 48 cores
[2020-06-22 20:32:30] Plotting identity distribution between each pair of groups
[2020-06-22 20:32:33] Analyzing Blast hits to get HGT candidates with 48 cores
[2020-06-22 20:32:35] Plotting flanking regions with 48 cores
[2020-06-22 20:49:52] Extracting nc sequences for BM predicted HGTs
[2020-06-22 20:49:54] Deleting temporary files
[2020-06-22 20:49:55] Done for Best-match approach!
[2020-06-22 20:49:55] Found grouping file taxonomy_g9_grouping.txt, input genomes were clustered into 9 groups
[2020-06-22 20:49:55] Get gene/genome member in gene/species tree for each BM predicted HGT
[2020-06-22 20:49:55] Prepare subset of taxonomy_all_combined_faa.fasta for building gene tree
[2020-06-22 20:49:57] Get species/gene tree for 3873 BM approach identified HGTs with 48 cores
[2020-06-22 20:51:51] Running Ranger-DTL2 with dated mode
[2020-06-22 20:51:54] Parsing Ranger prediction results
[2020-06-22 20:51:54] Add Ranger-DTL predicted direction to HGT_candidates.txt
[2020-06-22 20:51:54] Deleting temporary files
[2020-06-22 20:51:55] Done for Phylogenetic approach!
Traceback (most recent call last):
  File "/opt/modules/pkgs/anaconda/4.8/envs/metachip/bin/MetaCHIP", line 259, in <module>
    combine_multiple_level_predictions(args, config_dict)
  File "/opt/modules/pkgs/anaconda/4.8/envs/metachip/lib/python3.7/site-packages/MetaCHIP/BP.py", line 3502, in combine_multiple_level_predictions
    Get_circlize_plot(multi_level_detection, output_prefix, pwd_detected_HGT_txt, genome_to_taxon_dict, circos_HGT_R, pwd_plot_circos, detection_rank_list, taxon_rank_num, pwd_MetaCHIP_op_folder)
  File "/opt/modules/pkgs/anaconda/4.8/envs/metachip/lib/python3.7/site-packages/MetaCHIP/BP.py", line 3199, in Get_circlize_plot
    value = each_3_split[2]
IndexError: list index out of range
```
There are some plots in the output, but the `*_detected_HGTs.txt` file only has the headers.

**Comment by songweizhi** [comment]
Hi Surh,

this error occurred because of no HGT in file *_detected_HGTs.txt. An error causes of the failure of parsing Ranger-DTL's output has been fixed. can you please try again and see whether you still get this error?

Thanks,
Weizhi
